import type { Metadata } from "next";
import "@fortawesome/fontawesome-free/css/all.css";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import UserProvider from "@/UserProvider";
import CountProvider from "@/CountProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <CountProvider>
            <Navbar />
            <main className="p-5">{children}</main>
            <Toaster />
            {/* <Footer /> */}
          </CountProvider>
        </UserProvider>
      </body>
    </html>
  );
}
